name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  tag:
    name: Deploy plugin for new Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use desired version of php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Composer install and build # Remove or modify this step as needed
        run: |
          composer install
          composer update
          composer install --no-dev
          composer dump-autoload -o
      

      - name: Use Node.js 12.1.0
        uses: actions/setup-node@v4
        with:
          node-version: 12.1.0
      - uses: actions/checkout@master
      - name: Npm install and build
        run: |
          rm -r package-lock.json
          npm install -g grunt-cli
          npm i
          grunt release
